var TRK_NAME = {
  AF: "Arcuate Fascicle",
  ATR: "Anterior Thalamic Radiation",
  CA: "Commissure Anterior",
  CC_1: "Rostrum",
  CC_2: "Genu",
  CC_3: "Rostral Body (Premotor)",
  CC_4: "Anterior Midbody (Primary Motor)",
  CC_5: "Posterior Midbody (Primary Somatosensory)",
  CC_6: "Isthmus",
  CC_7: "Splenium",
  CG: "Cingulum",
  CST: "Corticospinal Tract",
  MLF: "Middle Longitudinal Fascicle",
  FPT: "Fronto-Pontine Tract",
  FX: "Fornix",
  ICP: "Inferior Cerebellar PPeduncle",
  IFO: "Inferior Occipito-Frontal Fascicle",
  ILF: "Inferior Longitudinal Fascicle",
  MCP: "Middle Cerebellar Peduncle",
  OR: "Optic Radiation",
  POPT: "Parieto‐Occipital Pontine",
  SCP: "Superior Cerebellar Peduncle",
  SLF_I: "Superior Longitudinal Fascicle I",
  SLF_II: "Superior Longitudinal Fascicle II",
  SLF_III: "Superior Longitudinal Fascicle III",
  STR: "Superior Thalamic Radiation",
  UF: "Uncinate Fascicle",
  CC: "Corpus Callosum - All",
  T_PREF: "Thalamo-Prefrontal",
  T_PREM: "Thalamo-Premotor",
  T_PREC: "Thalamo-Precentral",
  T_POSTC: "Thalamo-Postcentral",
  T_PAR: "Thalamo-Parietal",
  T_OCC: "Thalamo-Occipital",
  ST_FO: "Striato-fronto-orbital",
  ST_PREF: "Striato-Prefrontal",
  ST_PREM: "Striato-Premotor",
  ST_PREC: "Striato-Precentral",
  ST_POSTC: "Striato-Postcentral",
  ST_PAR: "Striato-Parietal",
  ST_OCC: "Striato-Occipital",
};
